### ISSUE TITLE
ometa 0.2.1

### ISSUE THREAD

**Issue by sjanecki** [bmavity/scss-js#1]
Could you publish ometa 0.2.1 to npm?

I can't install latest scss from npm beacuse of dependency problem.

Thank you!

**Comment by bmavity** [comment]
Whoops. Sorry about that. I will take a look.

**Comment by bmavity** [comment]
Should be able to install now. I am not positive as to how stable things are, so if you have any issues feel free to let me know. I have not been able to get time to improve it, though I hope it's coming soon.
