### ISSUE TITLE
scss 0.2.3; css selector ometa failed to load

### ISSUE THREAD

**Issue by sjanecki** [bmavity/scss-js#2]
You have a typo in index.js where you are loading file '/CssSelector.ometa' 
File name is in lowercase on file system '/cssSelector.ometa'
So please change index.js code or change file name to lowercase 'c'

thank you!

**Comment by bmavity** [comment]
Weird, it was working with my test file. I must be doing something wrong. ;) I changed the file name and pushed v0.2.4. Should be good to go now.
